title: Basavaraj Kaladagi
email: basukaladagi at gmail.com
description: Basu Kaladagi's website
url: "https://example.org"
twitter: basukaladagi89

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
